# Generated by Django 3.1.1 on 2021-08-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210810_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='videoUpload',
            field=models.FileField(upload_to=''),
        ),
    ]
