# Generated by Django 3.1.1 on 2021-08-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210810_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='videoUpload',
            field=models.FileField(default='default.mp4', upload_to='media/videos/'),
        ),
    ]
