# Generated by Django 3.1.1 on 2021-08-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210810_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='videoUpload',
            field=models.FileField(default='default.mp4', null=True, upload_to='django_project/media/'),
        ),
    ]
